/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "g.h"
#include "granular.h"
#include "khp.h"
#include "klp.h"

// Include compiled network files ------------------

#include "d_networkdata.h"
#include "ftest_networkdata.h"
#include "Gran.h"
#include "Pan2_networkdata.h"
#include "polymod3_networkdata.h"
#include "StagesEQ_networkdata.h"
#include "StagesFilter_networkdata.h"
#include "StagesPan_networkdata.h"
#include "Stages_networkdata.h"
#include "TableFilter_networkdata.h"
#include "track2_networkdata.h"
#include "track3_networkdata.h"
#include "track4_networkdata.h"
#include "track_networkdata.h"
#include "vec1_networkdata.h"
#include "vecEQ_networkdata.h"
#include "vecfade_networkdata.h"
#include "vecFilter_networkdata.h"
#include "vecGran_networkdata.h"
#include "vecPan_networkdata.h"
#include "vecP_networkdata.h"
#include "_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

